spring.application.name=StoreLink

server.servlet.context-path=/storelink

# conexion
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/storelink?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=tu_contrasena
# hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
